// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.857
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"context"
	"encoding/base64"
	"io"
)

func ShowSVG(svgContent []byte) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div id=\"render-svg\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Unsafe(string(svgContent)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ShowSVGScript().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func encodeAsDataURI(content []byte) string {
	return "data:image/svg+xml;base64," + base64.StdEncoding.EncodeToString(content)
}

func ShowSVGScript() templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_ShowSVGScript_676d`,
		Function: `function __templ_ShowSVGScript_676d(){console.log(
		"ShowSVGScript is running",
	);

  const renderEl = document.getElementById("render-svg");
  const containerWidth = renderEl.getBoundingClientRect().width;
  const containerHeight = renderEl.getBoundingClientRect().height;

  // skip over the xml version tag
  const svgEl = renderEl.lastChild;

  svgEl.id = "diagram";

  Zoom.attach();

  svgEl.setAttribute("width", ` + "`" + `${containerWidth}px` + "`" + `);
  svgEl.setAttribute("height", ` + "`" + `${containerHeight}px` + "`" + `);

}`,
		Call:       templ.SafeScript(`__templ_ShowSVGScript_676d`),
		CallInline: templ.SafeScriptInline(`__templ_ShowSVGScript_676d`),
	}
}

// Unsafe returns a content as is, without escaping.
func Unsafe(html string) templ.Component {
	return templ.ComponentFunc(func(_ context.Context, w io.Writer) (err error) {
		_, err = io.WriteString(w, html)
		return
	})
}

var _ = templruntime.GeneratedTemplate
